parameters:
#    dshtutorial.example.class: Dsh\tutorialBundle\Example

services:
#    dshtutorial.example:
#        class: %dshtutorial.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
